// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BoxCreate = {
    name: string;
    description?: (string | null);
};

export type BoxesPublic = {
    data: Array<BoxPublic>;
    count: number;
};

export type BoxPublic = {
    name: string;
    description?: (string | null);
    id: string;
    owner_id?: (string | null);
    owner_name?: (string | null);
    assignee_id?: (string | null);
    assignee_name?: (string | null);
    stage: BoxStage;
    doc_count: number;
    stage_done_count: number;
    total_pages: number;
    completed: boolean;
};

export type BoxStage = 'preparation' | 'scan' | 'quality_control' | 'completed';

export type BoxUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type DocCreate = {
    name: string;
    description?: (string | null);
    pages?: number;
};

export type DocPublic = {
    name: string;
    description?: (string | null);
    pages?: number;
    id: string;
    box_id: string;
    completed?: boolean;
    prepared_at?: (string | null);
    prepared_by_name?: (string | null);
    scanned_at?: (string | null);
    scanned_by_name?: (string | null);
    checked_at?: (string | null);
    checked_by_name?: (string | null);
};

export type DocsPublic = {
    data: Array<DocPublic>;
    count: number;
};

export type DocUpdate = {
    name?: (string | null);
    description?: (string | null);
    pages?: (number | null);
    completed?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type BoxesReadBoxesData = {
    limit?: number;
    q?: (string | null);
    skip?: number;
    stage?: (BoxStage | null);
};

export type BoxesReadBoxesResponse = (BoxesPublic);

export type BoxesCreateBoxData = {
    requestBody: BoxCreate;
};

export type BoxesCreateBoxResponse = (BoxPublic);

export type BoxesReadBoxData = {
    id: string;
};

export type BoxesReadBoxResponse = (BoxPublic);

export type BoxesUpdateBoxData = {
    id: string;
    requestBody: BoxUpdate;
};

export type BoxesUpdateBoxResponse = (BoxPublic);

export type BoxesDeleteBoxData = {
    id: string;
};

export type BoxesDeleteBoxResponse = (Message);

export type BoxesClaimBoxData = {
    id: string;
};

export type BoxesClaimBoxResponse = (BoxPublic);

export type BoxesUnclaimBoxData = {
    id: string;
};

export type BoxesUnclaimBoxResponse = (BoxPublic);

export type BoxesRejectBoxData = {
    id: string;
};

export type BoxesRejectBoxResponse = (BoxPublic);

export type DocsReadDocsData = {
    boxId: string;
};

export type DocsReadDocsResponse = (DocsPublic);

export type DocsCreateDocData = {
    boxId: string;
    requestBody: DocCreate;
};

export type DocsCreateDocResponse = (DocPublic);

export type DocsReadDocData = {
    id: string;
};

export type DocsReadDocResponse = (DocPublic);

export type DocsUpdateDocData = {
    id: string;
    requestBody: DocUpdate;
};

export type DocsUpdateDocResponse = (DocPublic);

export type DocsDeleteDocData = {
    id: string;
};

export type DocsDeleteDocResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);