"""claim boxes and track doc completion

Revision ID: 1e3dbd0af7fb
Revises: 41f14831a680
Create Date: 2026-08-11 19:46:49.908405

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1e3dbd0af7fb'
down_revision = '41f14831a680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('assignee_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'box', ['assignee_id'])
    op.create_foreign_key(None, 'box', 'user', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.add_column('doc', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doc', sa.Column('completed_by_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('doc_assignee_id_fkey'), 'doc', type_='foreignkey')
    op.create_foreign_key(None, 'doc', 'user', ['completed_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('doc', 'assignee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc', sa.Column('assignee_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doc', type_='foreignkey')
    op.create_foreign_key(op.f('doc_assignee_id_fkey'), 'doc', 'user', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.drop_column('doc', 'completed_by_id')
    op.drop_column('doc', 'completed_at')
    op.drop_constraint(None, 'box', type_='foreignkey')
    op.drop_constraint(None, 'box', type_='unique')
    op.drop_column('box', 'assignee_id')
    # ### end Alembic commands ###
