"""add assignee to doc

Revision ID: 41f14831a680
Revises: ecba0060ebc9
Create Date: 2026-08-09 19:04:04.949949

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '41f14831a680'
down_revision = 'ecba0060ebc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc', sa.Column('assignee_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'doc', 'user', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doc', type_='foreignkey')
    op.drop_column('doc', 'assignee_id')
    # ### end Alembic commands ###
