"""unique box and doc names

Revision ID: 5b96bcaab621
Revises: b6d0e8aa0d38
Create Date: 2026-08-21 18:03:41.295090

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5b96bcaab621'
down_revision = 'b6d0e8aa0d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_box_name_lower', 'box', [sa.literal_column('lower(name)')], unique=True)
    op.create_index('ix_doc_name_lower', 'doc', [sa.literal_column('lower(name)')], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doc_name_lower', table_name='doc')
    op.drop_index('ix_box_name_lower', table_name='box')
    # ### end Alembic commands ###
