"""add pipeline stages

Revision ID: b6d0e8aa0d38
Revises: c4fc02482298
Create Date: 2026-08-18 13:27:36.185138

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6d0e8aa0d38'
down_revision = 'c4fc02482298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('stage', sa.String(length=32), nullable=False, server_default='preparation'))
    op.create_index(op.f('ix_box_stage'), 'box', ['stage'], unique=False)
    op.add_column('doc', sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doc', sa.Column('prepared_by_id', sa.Uuid(), nullable=True))
    op.add_column('doc', sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doc', sa.Column('scanned_by_id', sa.Uuid(), nullable=True))
    op.add_column('doc', sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doc', sa.Column('checked_by_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('doc_completed_by_id_fkey'), 'doc', type_='foreignkey')
    op.create_foreign_key(None, 'doc', 'user', ['checked_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'doc', 'user', ['prepared_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'doc', 'user', ['scanned_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('doc', 'completed_by_id')
    op.drop_column('doc', 'completed')
    op.drop_column('doc', 'completed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('doc', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('doc', sa.Column('completed_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doc', type_='foreignkey')
    op.drop_constraint(None, 'doc', type_='foreignkey')
    op.drop_constraint(None, 'doc', type_='foreignkey')
    op.create_foreign_key(op.f('doc_completed_by_id_fkey'), 'doc', 'user', ['completed_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('doc', 'checked_by_id')
    op.drop_column('doc', 'checked_at')
    op.drop_column('doc', 'scanned_by_id')
    op.drop_column('doc', 'scanned_at')
    op.drop_column('doc', 'prepared_by_id')
    op.drop_column('doc', 'prepared_at')
    op.drop_index(op.f('ix_box_stage'), table_name='box')
    op.drop_column('box', 'stage')
    # ### end Alembic commands ###
