"""keep boxes when owner is deleted

Revision ID: c4fc02482298
Revises: 1e3dbd0af7fb
Create Date: 2026-08-13 16:31:12.744398

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c4fc02482298'
down_revision = '1e3dbd0af7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('box', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('box_owner_id_fkey'), 'box', type_='foreignkey')
    op.create_foreign_key(None, 'box', 'user', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'box', type_='foreignkey')
    op.create_foreign_key(op.f('box_owner_id_fkey'), 'box', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('box', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
