"""add pages to doc

Revision ID: ecba0060ebc9
Revises: ca2237323570
Create Date: 2026-08-05 17:22:03.867066

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ecba0060ebc9'
down_revision = 'ca2237323570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc', sa.Column('pages', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc', 'pages')
    # ### end Alembic commands ###
